/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/lySIxl57VnC
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { DM_Sans } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

dm_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link";
import { Select } from "@/components/ui/select";
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Slider } from "@/components/ui/slider";
import { Checkbox } from "@/components/ui/checkbox";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { ResponsiveLine } from "@nivo/line";

export function Component() {
  return (
    <div className="flex flex-col min-h-screen w-full">
      <header className="flex items-center justify-between bg-background px-4 py-3 shadow-sm sm:px-6">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <UserIcon className="h-6 w-6" />
          <span className="text-lg font-medium">UI Helper</span>
        </Link>
        <Link
          href="#"
          className="text-muted-foreground hover:text-foreground"
          prefetch={false}
        >
          <GitlabIcon className="h-6 w-6" />
          <span className="sr-only">GitHub</span>
        </Link>
      </header>
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-6 p-4 sm:p-6">
        <div className="flex flex-col gap-6">
          <div className="flex items-center justify-between">
            <label htmlFor="settings" className="text-sm font-medium">
              Settings
            </label>
            <Select id="settings" className="w-auto">
              <option value="option1">Option 1</option>
              <option value="option2">Option 2</option>
              <option value="option3">Option 3</option>
            </Select>
          </div>
          <div className="grid gap-4">
            <Card>
              <CardHeader>
                <CardTitle>UI Controls</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="grid grid-cols-2 gap-4">
                    <Button variant="outline">Button 1</Button>
                    <Button variant="outline">Button 2</Button>
                  </div>
                  <Slider
                    min={0}
                    max={100}
                    defaultValue={[50]}
                    aria-label="Slider"
                  />
                  <Checkbox id="checkbox1" defaultChecked>
                    Checkbox
                  </Checkbox>
                  <Switch id="switch1" defaultChecked>
                    Switch
                  </Switch>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
        <div className="flex flex-col gap-6">
          <Card className="flex-1">
            <CardHeader>
              <CardTitle>Graph</CardTitle>
            </CardHeader>
            <CardContent>
              <LineChart className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
          <Tabs defaultValue="code">
            <TabsList>
              <TabsTrigger value="code">Code</TabsTrigger>
              <TabsTrigger value="data">Data</TabsTrigger>
            </TabsList>
            <TabsContent value="code">
              <Card className="flex-1">
                <CardHeader>
                  <CardTitle>React Code</CardTitle>
                </CardHeader>
                <CardContent>
                  <pre className="overflow-auto p-4 bg-muted rounded-md">{`
function Component() {
  return (
    <div className="flex flex-col min-h-screen w-full">
      <header className="flex items-center justify-between bg-background px-4 py-3 shadow-sm sm:px-6">
        <Link href="/" className="flex items-center gap-2">
          <Icon prompt="UI Helper" className="h-6 w-6" />
          <span className="text-lg font-medium">UI Helper</span>
        </Link>
        <Link href="https://github.com/ui-helper" className="text-muted-foreground hover:text-foreground">
          <Icon prompt="GitHub" className="h-6 w-6" />
          <span className="sr-only">GitHub</span>
        </Link>
      </header>
      <main className="flex-1 grid grid-cols-1 md:grid-cols-2 gap-6 p-4 sm:p-6">
        <div className="flex flex-col gap-6">
          <div className="flex items-center justify-between">
            <label htmlFor="settings" className="text-sm font-medium">
              Settings
            </label>
            <Select id="settings" className="w-auto">
              <option value="option1">Option 1</option>
              <option value="option2">Option 2</option>
              <option value="option3">Option 3</option>
            </Select>
          </div>
          <div className="grid gap-4">
            <Card>
              <CardHeader>
                <CardTitle>UI Controls</CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid gap-4">
                  <div className="grid grid-cols-2 gap-4">
                    <Button variant="outline">Button 1</Button>
                    <Button variant="outline">Button 2</Button>
                  </div>
                  <Slider
                    min={0}
                    max={100}
                    defaultValue={50}
                    aria-label="Slider"
                  />
                  <Checkbox id="checkbox1" defaultChecked>
                    Checkbox
                  </Checkbox>
                  <Switch id="switch1" defaultChecked>
                    Switch
                  </Switch>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
        <div className="flex flex-col gap-6">
          <Card className="flex-1">
            <CardHeader>
              <CardTitle>Graph</CardTitle>
            </CardHeader>
            <CardContent>
              <Chart prompt="A line chart with two lines" className="w-full aspect-[4/3]" />
            </CardContent>
          </Card>
          <Tabs defaultValue="code">
            <TabsList>
              <TabsTrigger value="code">Code</TabsTrigger>
              <TabsTrigger value="data">Data</TabsTrigger>
            </TabsList>
            <TabsContent value="code">
              <Card className="flex-1">
                <CardHeader>
                  <CardTitle>React Code</CardTitle>
                </CardHeader>
                <CardContent>
                  <pre className="overflow-auto p-4 bg-muted rounded-md">
                    {/* Code content goes here */}
                  </pre>
                </CardContent>
              </Card>
            </TabsContent>
            <TabsContent value="data">
              <Card className="flex-1">
                <CardHeader>
                  <CardTitle>JSON Data</CardTitle>
                </CardHeader>
                <CardContent>
                  <pre className="overflow-auto p-4 bg-muted rounded-md">
                    {/* Data content goes here */}
                  </pre>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      </main>
    </div>
  )
}
                    `}</pre>
                </CardContent>
              </Card>
            </TabsContent>
            <TabsContent value="data">
              <Card className="flex-1">
                <CardHeader>
                  <CardTitle>JSON Data</CardTitle>
                </CardHeader>
                <CardContent>
                  <pre className="overflow-auto p-4 bg-muted rounded-md">
                    {JSON.stringify(
                      {
                        desktop: [
                          { month: "January", value: 186 },
                          { month: "February", value: 305 },
                          { month: "March", value: 237 },
                          { month: "April", value: 73 },
                          { month: "May", value: 209 },
                          { month: "June", value: 214 },
                        ],
                        mobile: [
                          { month: "January", value: 80 },
                          { month: "February", value: 200 },
                          { month: "March", value: 120 },
                          { month: "April", value: 190 },
                          { month: "May", value: 130 },
                          { month: "June", value: 140 },
                        ],
                      },
                      null,
                      2
                    )}
                  </pre>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      </main>
    </div>
  );
}

function GitlabIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 13.29-3.33-10a.42.42 0 0 0-.14-.18.38.38 0 0 0-.22-.11.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18l-2.26 6.67H8.32L6.1 3.26a.42.42 0 0 0-.1-.18.38.38 0 0 0-.26-.08.39.39 0 0 0-.23.07.42.42 0 0 0-.14.18L2 13.29a.74.74 0 0 0 .27.83L12 21l9.69-6.88a.71.71 0 0 0 .31-.83Z" />
    </svg>
  );
}

function LineChart(props: any) {
  return (
    <div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application"
      />
    </div>
  );
}

function UserIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  );
}
